# Generated by Django 5.2 on 2025-05-15 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=205)),
                ('topic', models.CharField(max_length=150)),
                ('tags', models.JSONField()),
                ('text', models.TextField()),
                ('links', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='profile/<django.db.models.fields.related.ForeignKey>/posts/images')),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
