# Generated by Django 5.2 on 2025-05-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_posts_app', '0002_alter_user_post_images_alter_user_post_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='images',
        ),
        migrations.CreateModel(
            name='Images_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_posts_app.user_post')),
            ],
        ),
    ]
