# Generated by Django 5.2 on 2025-05-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_posts_app', '0003_remove_user_post_images_images_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
