# Generated by Django 5.2.1 on 2025-06-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_posts_app', '0006_image_tag_remove_user_post_user_post_link_album_and_more'),
        ('user_app', '0003_alter_avatar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='user_app.profile'),
            preserve_default=False,
        ),
    ]
