# Generated by Django 5.2 on 2025-06-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='subitle',
            new_name='subtitle',
        ),
    ]
