# Generated by Django 5.2 on 2025-06-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_albumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
