# Generated by Django 5.2 on 2025-06-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_album_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
    ]
