# Generated by Django 5.2 on 2025-06-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        ('user_app', '0003_alter_avatar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='admin',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='administered_group', to='user_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='user_app.profile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile'),
            preserve_default=False,
        ),
    ]
