# Generated by Django 5.2 on 2025-06-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
