# Generated by Django 5.2 on 2025-05-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
