# Generated by Django 5.2 on 2025-06-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customabstractuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
