# Generated by Django 5.2 on 2025-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_profile_email_remove_profile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
