# Generated by Django 5.2 on 2025-06-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customabstractuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customabstractuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/ranalda.jpg', null=True, upload_to='images/'),
        ),
    ]
