# Generated by Django 5.2 on 2025-05-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_registrationcodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
