# Generated by Django 5.2 on 2025-06-07 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_customabstractuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customabstractuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrationcodes',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
