# Generated by Django 5.2 on 2025-05-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_profile_birthday_profile_request_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
