# Generated by Django 5.2 on 2025-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_customabstractuser_friend_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customabstractuser',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
